### ISSUE TITLE
login and logout with socket.io

### ISSUE THREAD

**Issue by Lichtjaeger** [jfromaniello/passport.socketio#108]
I’m looking for something like:

```javascript
socket.on('login', function(username, password) {
	if (verify(username, password)) {
		socket.request.login(user,  function(err) {
			console.log("io: login");
			if (err) {
				console.log(err);
			}
			//...
		});
	}
});
socket.on('logout', function() {
	socket.request.logout();
	console.log('io: logout');
	//...
});
```

So I can login/logout a user with socket.io and use the user object on express and socket.io.

It seems there is already an implementation of these functions, but .logout() doesn’t work and .login() throws the following message:

```
Missing error handler on `socket`.
Error: passport.initialize() middleware not in use
    at IncomingMessage.req.login.req.logIn (...\node_modules\passport\lib\http\request.js:44:34)
    at Socket.<anonymous> (...\app.js:131:18)
    at Socket.emit (events.js:104:17)
    at Socket.onevent (...\node_modules\socket.io\lib\socket.js:330:8)
    at Socket.onpacket (...\node_modules\socket.io\lib\socket.js:290:12)
    at Client.ondecoded (...\node_modules\socket.io\lib\client.js:193:14)
    at Decoder.Emitter.emit (...\node_modules\socket.io\node_modules\socket.io-parser\node_modules\component-emitter\index.js:134:20)
    at Decoder.add (...\node_modules\socket.io\node_modules\socket.io-parser\index.js:247:12)
    at Client.ondata (...\node_modules\socket.io\lib\client.js:175:18)
    at Socket.emit (events.js:107:17)
```

**Comment by jfromaniello** [comment]
This module allows you to use the passport.js session in a socket.io communication, it is not meant to authenticate. Passport.js is an authentication framework for Express.js not socket.io.
