### ISSUE TITLE
Missing error handler on `socket`.     TypeError: Cannot read property 'findOne' of undefined

### ISSUE THREAD

**Issue by Lenny-Hu** [jfromaniello/passport.socketio#133]
"socket.io": "1.7.2"
"passport.socketio": "~3.7.0",
"passport": "~0.3.2",

有的时候，启动服务器时正好有用户使用socket来连接时，会出现这个错误，请问这是为啥？
Sometimes, arrives at server startup when the user use the socket connection, will appear this mistake.

```
$ ./main.sh -vn
### enable debug message
### NOT build all the coffee and iced scripts
### load config.sh
### automatically kill the old process
./main.sh: line 76: pidof: command not found
### nothing to kill.
连接成功
Sat, 01 Apr 2017 09:42:06 GMT app database connected
4/1 17:42:07.050 - debug - web server listening on port 5000
Sat, 01 Apr 2017 09:42:07 GMT socket 启动客户端管理...
Sat, 01 Apr 2017 09:42:07 GMT socket 启动agent管理...
Mongoose: users.ensureIndex({ username: 1 }) { unique: true, background: true }
Mongoose: tasks.ensureIndex({ originalId: 1 }) { background: true }
Mongoose: taskqueues.ensureIndex({ originalId: 1 }) { background: true }
Missing error handler on `socket`.
TypeError: Cannot read property 'findOne' of undefined
    at MongoSessionStore.get (D:\web\Backend\node_modules\sessionstore\lib\databases\mongodb.js:209:54)
    at Array.<anonymous> (D:\web\Backend\node_modules\passport.socketio\lib\index.js:75:16)
    at run (D:\WebImager\web\node_modules\socket.io\lib\namespace.js:119:11)
    at Namespace.run (D:\web\Backend\node_modules\socket.io\lib\namespace.js:131:3)
    at Namespace.add (D:\web\Backend\node_modules\socket.io\lib\namespace.js:160:8)
    at Client.connect (D:\web\Backend\node_modules\socket.io\lib\client.js:76:20)
    at Client.ondecoded (D:\web\Backend\node_modules\socket.io\lib\client.js:190:10)
    at Decoder.Emitter.emit (D:\web\Backend\node_modules\component-emitter\index.js:134:20)
    at Decoder.add (D:\web\Backend\node_modules\socket.io-parser\index.js:246:12)
    at Client.ondata (D:\web\Backend\node_modules\socket.io\lib\client.js:176:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Socket.onPacket (D:\web\Backend\node_modules\engine.io\lib\socket.js:102:14)
    at emitOne (events.js:96:13)
    at XHR.emit (events.js:188:7)
    at XHR.Transport.onPacket (D:\web\Backend\node_modules\engine.io\lib\transport.js:105:8)

```

**socket-manager.iced**

```
passportSocketIo = require("passport.socketio")
socketMap.Clients = ioServer.of "/clients/"

socketMap.Clients.use passportSocketIo.authorize {cookieParser: require('cookie-parser'), key, secret, store, success, fail, passport}
```

**Comment by Lenny-Hu** [comment]
是因为sessions这个数据库连接未完成导致的，不好意思。
